# GENERATED by ./pkgs/applications/editors/vim/plugins/update.py. Do not edit!
{
  lib,
  buildVimPlugin,
  buildNeovimPlugin,
  fetchFromGitHub,
  fetchgit,
}:

final: prev: {
  nvim-silicon = buildVimPlugin {
    pname = "nvim-silicon";
    version = "2024-07-30";
    src = fetchFromGitHub {
      owner = "michaelrommel";
      repo = "nvim-silicon";
      rev = "feb882f04c992b797daa118101a239fb3bedfc04";
      sha256 = "03dy4q2dbgiyydi9wvpij6s2aggdpr3lgd9cqqv0i2m1m0qb9gad";
    };
    meta.homepage = "https://github.com/michaelrommel/nvim-silicon/";
  };

  vim-jjdescription = buildVimPlugin {
    pname = "vim-jjdescription";
    version = "2024-05-28";
    src = fetchFromGitHub {
      owner = "avm99963";
      repo = "vim-jjdescription";
      rev = "ca14325202f3cd894d01ba833451017624249222";
      sha256 = "1y83fdih991ivlvgcwp0sx97icmf9k6px7mr26vb77izjlf011w2";
    };
    meta.homepage = "https://github.com/avm99963/vim-jjdescription/";
  };

}
