# GENERATED by ./pkgs/applications/editors/vim/plugins/update.py. Do not edit!
{
  lib,
  buildVimPlugin,
  buildNeovimPlugin,
  fetchFromGitHub,
  fetchgit,
}:

final: prev: {
  nvim-silicon = buildVimPlugin {
    pname = "nvim-silicon";
    version = "2024-08-31";
    src = fetchFromGitHub {
      owner = "michaelrommel";
      repo = "nvim-silicon";
      rev = "9fe6001dc8cad4d9c53bcfc8649e3dc76ffa169c";
      sha256 = "1qczi06yndkr2pmwidlkgmk0395x189sznvscn4fnr96jx58j5yl";
    };
    meta.homepage = "https://github.com/michaelrommel/nvim-silicon/";
  };

}
