on:
  push:
  schedule:
    - cron: '12 5 * * *'
jobs:
  check:
    runs-on: nixos
    steps:
      - uses: "https://code.forgejo.org/actions/checkout@v4"
      - run: nix --version
      - run: nix flake check --keep-going --verbose
  build:
    runs-on: nixos
    strategy:
      matrix:
        target:
          - audiomenu
          - docs
          - jpassmenu
          - nixosConfigurations.vm.config.system.build.toplevel
          - nvim
    steps:
      - uses: "https://code.forgejo.org/actions/checkout@v4"
      - run: nix --version
      - run: nix build --print-build-logs '.#${{ matrix.target }}'
  update-lockfile:
    needs: [check build]
    runs-on: nixos
    if: github.event_name == 'schedule'
    steps:
      - uses: "https://code.forgejo.org/actions/checkout@v4"
      - run: nix --version
      - run: nix flake update
      - name: nix flake update
        run: |
          git config user.name 'forgejo-actions'
          git config user.email 'forgejo-actions@noreply.salame.cl'
          nix flake update --commit-lock-file --option commit-lockfile-summary '[chore] flake.lock: update inputs'
      - run: nix flake check --keep-going --verbose
      - run: git push
