on:
  push:
jobs:
  check-fmt:
    runs-on: nixos
    steps:
      - uses: https://git.salame.cl/actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: nix --version
      - name: Run treefmt
        run: |
          nix build --print-build-logs ".#checks.$(nix eval --raw --impure --expr builtins.currentSystem).treefmt"
  build-package:
    runs-on: nixos
    needs: check-fmt
    strategy:
      matrix:
        package:
          - audiomenu
          - docs
          - docs-home-markdown
          - docs-nixos-markdown
          - docs-nvim-markdown
          - jpassmenu
          - nvim
          - nvim-headless
          - nvim-no-lsps
          - nvim-no-ts
          - nvim-small
          - search
    steps:
      - uses: "https://git.salame.cl/actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4
      - run: nix --version
      - name: Build target
        env:
          PACKAGE: ${{ matrix.package }}
        run: |
          # shellcheck disable=SC2016
          nix build --print-build-logs ".#$PACKAGE"
  check-nvim:
    runs-on: nixos
    needs: build-package
    strategy:
      matrix:
        nvim:
          - nvim
          - nvim-headless
          - nvim-no-lsps
          - nvim-no-ts
          - nvim-small
    steps:
      - uses: "https://git.salame.cl/actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4
      - run: nix --version
      - name: Build target
        env:
          NVIM: ${{ matrix.nvim }}
        run: |
          nix build --print-build-logs ".#checks.$(nix eval --raw --impure --expr builtins.currentSystem).$NVIM"
  build-vm:
    runs-on: nixos
    needs:
      - build-package
      - check-nvim
    steps:
      - uses: "https://git.salame.cl/actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4
      - run: nix --version
      - name: Build VM configuration
        run: |
          nix build --print-build-logs '.#nixosConfigurations.vm.config.system.build.toplevel'
  build-hm:
    runs-on: nixos
    needs:
      - build-package
      - check-nvim
    steps:
      - uses: "https://git.salame.cl/actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4
      - run: nix --version
      - name: Build Home Manager configuration
        run: |
          nix build --print-build-logs '.#homeConfigurations.example.activationPackage'
  report-size:
    runs-on: nixos
    needs:
      - build-vm
      - build-hm
    steps:
      - uses: "https://git.salame.cl/actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4
      - run: nix --version
      - name: Create Size Report
        uses: "https://git.salame.cl/jalil/nix-flake-outputs-size@1b14f63169bc6721bb65ba6a43cc5e5379f46b66" # main
        with:
          # Create a comment on the associated PR
          comment-on-pr: ${{ github.ref_name != 'main' }}
          # Generate artifacts on main (to speed up comparisons)
          generate-artifact: ${{ github.ref_name == 'main' }}
          # Generate comparisons to main
          do-comparison: 'true'
          # This job's name (so we can find the artifacts)
          job-name: report-size
