on: [push]
jobs:
  check:
    runs-on: nixos
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
      - run: nix --version
      - run: nix flake check --keep-going --verbose
  build:
    runs-on: nixos
    strategy:
      matrix:
        target:
          - docs
          - nvim
          - nixosConfigurations.vm.config.system.build.toplevel
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
      - run: nix --version
      - run: nix build --print-build-logs '.#${{ matrix.target }}'
