on:
  push:
    paths:
      # only run if the renovate config changed
      - renovate.json
jobs:
  check-renovaterc:
    runs-on: nixos
    steps:
      - uses: https://git.salame.cl/actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - run: nix --version
      - name: Validate renovaterc.json
        run: |
          nix shell nixpkgs#renovate --command renovate-config-validator
