[book]
authors = ["Jalil David Salamé Messina"]
language = "en"
multilingual = false
src = "src"
title = "Jalil's NixOS configuration modules"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
